project:
  type: website
  render:
    - "*.qmd"
    - "!readme.qmd"
    - "!*.md"
    - "!template_results.qmd"
execute: 
  freeze: auto  # re-render only when source changes
website:
  title: "Exploring the OpenPrescribing Dataset"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: Bradford_analysis.qmd
        text: Bradford
      - href: detailed_Bradford.qmd
        text: Bradford detailed
      - section: Multiple regions
        contents: 
          - href: Multiple_regions_analysis.qmd
            text: Extracting data
          - href: detailed_results.qmd
            text: Results
      - section: GP Practices Analysis
        contents: 
          - href: Practices_analysis.qmd
            text: GP Practices location analysis
          - href: registered_patients.qmd
            text: Registered patients
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true