---
title: "GP Practices Classification"
editor: source
execute: 
  warning: false
  error: false
---

Packages

```{r}
library(sf)
library(tidyverse)
library(tmap)
```

Loading the CAZ boundaries


```{r}
CAZ_boundaries <- st_read("CAZ_boundaries.gpkg")
```

We will produce two buffers for each CAZ: 1 km and 10 km.

```{r}
CAZ_buffer_1k <-  CAZ_boundaries |> 
  st_buffer(1e3)
CAZ_buffer_5k <-  CAZ_boundaries |> 
  st_buffer(5e3)
```

```{r}
tmap_mode("view")

tm_shape(CAZ_buffer_5k)+
  tm_fill("dodgerblue",alpha = 0.3)+
  tm_shape(CAZ_buffer_1k)+
  tm_fill("dodgerblue3",alpha = 0.3)+
tm_shape(CAZ_boundaries)+
  tm_fill("darkblue")
  
```

Loading all data from previous analysis

```{r}
load("all_data.RData")
```

Let's classify the CAZ based on their location. 


```{r}
all_practices_raw$within_CAZ <- st_intersects(all_practices_raw,CAZ_boundaries) |> vapply(length,numeric(1)) > 0
all_practices_raw$within_1km <- st_intersects(all_practices_raw,CAZ_buffer_1k) |> vapply(length,numeric(1)) > 0
all_practices_raw$within_5km <- st_intersects(all_practices_raw,CAZ_buffer_5k) |> vapply(length,numeric(1)) > 0

all_practices_raw$location_class <- case_when(all_practices_raw$within_CAZ~"within_CAZ",
                                              all_practices_raw$within_1km~"within_1km",
                                              all_practices_raw$within_5km~"within_5km",
                                              TRUE~"out_CAZ")
                                              
                                              


all_practices_raw$CAZ_index <- st_intersects(all_practices_raw,CAZ_buffer_5k) |> vapply(first,integer(1))
all_practices_raw$CAZ_name <- CAZ_buffer_5k$name[all_practices_raw$CAZ_index]
```

Visualising the results for the classification
```{r}
tmap_mode("plot")
tm_shape(all_practices_raw)+
  tm_dots("location_class")

tm_shape(all_practices_raw)+
  tm_dots("CAZ_name")
```


```{r}
st_write(all_practices_raw,"practices_CAZ.gpkg",append = F)
```


Saving the results as a release of the repo
```{r}
#| eval: false

system("gh release upload v0 practices_CAZ.gpkg --clobber")
```

